# -*- coding: utf-8 -*-
"""BankNote_ML

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1L8TfQYKwD15QOnicBrdaCSUhqGy0tqqr
"""

import os
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
import pickle

from google.colab import drive
drive.mount('/content/drive')

import warnings
warnings.filterwarnings('ignore')

data = pd.read_csv("BankNote_Authentication.csv")

X=data.iloc[:,:-1]
y=data.iloc[:,-1]

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=0)

classifier=RandomForestClassifier()
classifier.fit(X_train,y_train)

y_pred=classifier.predict(X_test)

from sklearn.metrics import accuracy_score
score=accuracy_score(y_test,y_pred)

score

pickle_out = open("BankNote.pkl","wb")
pickle.dump(classifier, pickle_out)
pickle_out.close()

classifier.predict([[2,3,4,1]])



